version: '3.7'
services:
  services-content:
    container_name: services-content
    build:
      context: ./applications/services/content
    volumes:
      - services-content-sync:/app:nocopy
      - app/node_modules
    ports:
      - "4001:4001"
    command: yarn start
  web-content:
    container_name: web-content
    build:
      context: ./applications/web/content
    volumes:
      - web-content-sync:/app:nocopy
      - app/node_modules
    ports:
      - "3001:3001"
      - "8080:8080"
    command: yarn start
volumes:
  services-content-sync:
    external: true
  web-content-sync:
    external: true
